package com.caracal.initializr.dao;

import com.caracal.initializr.model.Project;
import com.caracal.data.impl.AbstractDAOImpl;
import org.springframework.stereotype.Repository;


/* Generated By Nicico System Generator ( Powered by Dr.Adldoost :D ) */

@Repository
public class ProjectDao extends AbstractDAOImpl<Project, Long> {

    public ProjectDao() {
        super(Project.class);
    }
}
